### ISSUE TITLE
there is no options to provide the numWorkers and autoscalingAlgorithm 

### ISSUE THREAD

**Issue by saravana1992** [terraform-google-modules/terraform-google-dataflow#17]
Hi Team

There are no options to provide the numWorkers and autoscalingAlgorithm.
Which is basically supported by the gcloud cli.

URL : https://cloud.google.com/dataflow/docs/guides/specifying-exec-params

**Comment by bharathkkb** [comment]
@saravana1992 I believe these can be passed in through the `parameters` var.
https://github.com/terraform-google-modules/terraform-google-dataflow/blob/f91e26d032f1a10e363c73ff734e93e26b774894/variables.tf#L36
```tf
.
.
parameters = {
    numWorkers = 1
    autoscalingAlgorithm = "THROUGHPUT_BASED"
}
```

**Comment by shermanericts** [comment]
> @saravana1992 I believe these can be passed in through the `parameters` var.
> https://github.com/terraform-google-modules/terraform-google-dataflow/blob/f91e26d032f1a10e363c73ff734e93e26b774894/variables.tf#L36
> 
> ```terraform
> .
> .
> parameters = {
>     numWorkers = 1
>     autoscalingAlgorithm = "THROUGHPUT_BASED"
> }
> ```
> 
> Additional example with params here:
> https://github.com/terraform-google-modules/terraform-google-dataflow/blob/f91e26d032f1a10e363c73ff734e93e26b774894/examples/dlp_api_example/main.tf#L110

Thanks @bharathkkb  !
I saw this was still an open issue.  Trying this out right now.  Not sure if there was any update.

Also, is there a way to pass `--disk_size_gb` ? Also  as a parameter?
thx again.

**Comment by shermanericts** [comment]
> > @saravana1992 I believe these can be passed in through the `parameters` var.
> > https://github.com/terraform-google-modules/terraform-google-dataflow/blob/f91e26d032f1a10e363c73ff734e93e26b774894/variables.tf#L36
> > 
> > ```terraform
> > .
> > .
> > parameters = {
> >     numWorkers = 1
> >     autoscalingAlgorithm = "THROUGHPUT_BASED"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Additional example with params here:
> > https://github.com/terraform-google-modules/terraform-google-dataflow/blob/f91e26d032f1a10e363c73ff734e93e26b774894/examples/dlp_api_example/main.tf#L110
> 
> Thanks @bharathkkb !
> I saw this was still an open issue. Trying this out right now. Not sure if there was any update.
> 
> Also, is there a way to pass `--disk_size_gb` ? Also as a parameter?
> thx again.

This was my bad.  For Java dataflow options you need to pass the params as camel case.  Then it works.  this can be closed.
